services:
  app:
    build:
      dockerfile: src/Dockerfile
      context: .
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
